# App store edition names: every real name in the game -> its changed version (the website keeps the real names)
PLAYERS = {
"Scottie Scheffler":"Scotty Shefford","Rory McIlroy":"Rory McIlvane","Cameron Young":"Cameron Youngs","Matt Fitzpatrick":"Matt Fitzpatrice",
"Justin Rose":"Justin Rosen","Collin Morikawa":"Colin Morimoto","Tommy Fleetwood":"Tommy Fleetwell","Xander Schauffele":"Xander Schaufeld",
"J.J. Spaun":"J.J. Spawn","Chris Gotterup":"Chris Gotteridge","Russell Henley":"Russell Hensley","Jon Rahm":"Jon Rahmer",
"Ludvig Aberg":"Ludvig Abergson","Robert MacIntyre":"Robert MacIntosh","Aaron Rai":"Aaron Raine","Justin Thomas":"Justin Tomlin",
"Ben Griffin":"Ben Griffith","Sepp Straka":"Sepp Strakov","Hideki Matsuyama":"Hideki Matsumoto","Alex Noren":"Alex Norell",
"Patrick Reed":"Patrick Reede","Harris English":"Harris Englund","Jacob Bridgeman":"Jacob Bridgewater","Si Woo Kim":"Si Woo Kang",
"Tom Kim":"Tom Kang","Kristoffer Reitan":"Kristoffer Reitstad","Akshay Bhatia":"Akshay Bhatti","Tyrrell Hatton":"Tyrrell Hatfield",
"Nicolai Hojgaard":"Nicolai Hojberg","Kurt Kitayama":"Kurt Kitamura","Viktor Hovland":"Viktor Hoveland","Min Woo Lee":"Min Woo Leigh",
"Bryson DeChambeau":"Bryson DuChamp","Patrick Cantlay":"Patrick Cantwell","Maverick McNealy":"Maverick McNeely","Sam Burns":"Sam Burnside",
"Kristoffer Ventura":"Kristoffer Venturo","Jackson Suber":"Jackson Suberly","Keegan Bradley":"Keegan Bradbury","Sudarshan Yellamaraju":"Sudarshan Yellamanchi",
"Zecheng Dou":"Zecheng Dao","Mac Meissner":"Mac Meisner","Eric Cole":"Eric Coles","Zach Bauchou":"Zach Beauchamp",
"A.J. Ewart":"A.J. Ewing","Ryan Gerard":"Ryan Girard","Rickie Fowler":"Rickie Fowles","Jake Knapp":"Jake Knappe",
"Shane Lowry":"Shane Lowery","Jason Day":"Jason Daye","Alex Smalley":"Alex Smalling","Marco Penge":"Marco Pengelly",
"Daniel Berger":"Daniel Bergen","Michael Kim":"Michael Kang","Matt McCarty":"Matt McCartney","Jordan Spieth":"Jordan Speight",
"Gary Woodland":"Gary Woodlands","Adam Scott":"Adam Scotts","Nicolas Echavarria":"Nicolas Echeverri","Sam Stevens":"Sam Stephens",
"Corey Conners":"Corey Connors","Andrew Novak":"Andrew Novacek","Ryan Fox":"Ryan Foxx","Brian Harman":"Brian Hartman",
"Michael Brennan":"Michael Brennand","Pierceson Coody":"Pierceson Cody","David Puig":"David Puigdemont","Nick Taylor":"Nick Tayler",
"Keith Mitchell":"Keith Mitchum","Steven Fisk":"Steven Fiske","Ryo Hisatsune":"Ryo Hisamatsu","Kevin Yu":"Kevin Yue",
"Davis Thompson":"Davis Thomsen","Mackenzie Hughes":"Mackenzie Hewes","Brooks Koepka":"Brooks Koepke","Billy Horschel":"Billy Horshell",
"Harry Hall":"Harry Halle","Sami Valimaki":"Sami Valimaa","Max Greyserman":"Max Greysman","Pontus Nyholm":"Pontus Nyberg",
"Adrien Dumont de Chassart":"Adrien Dupont de Chassard","Davis Chatfield":"Davis Chatham","Thomas Detry":"Thomas Detroy","Rico Hoey":"Rico Hoye",
"William Mouw":"William Mouwe","Karl Vilips":"Karl Vilipsen","Emiliano Grillo":"Emiliano Grilli","Austin Eckroat":"Austin Eckrote",
"Lee Hodges":"Lee Hodgson","Matti Schmid":"Matti Schmidt","Bud Cauley":"Bud Cawley","Rasmus Hojgaard":"Rasmus Hojberg",
"Jayden Schaper":"Jayden Schapiro","Matt Wallace":"Matt Wallis","Michael Thorbjornsen":"Michael Thorbjorn","Jordan Smith":"Jordan Smyth",
"Sungjae Im":"Sungjae Lim","Casey Jarvis":"Casey Jervis","Aldrich Potgieter":"Aldrich Potgeter","Wyndham Clark":"Wyndham Clarke",
"Patrick Rodgers":"Patrick Rogers","John Keefer":"John Keefe","Sahith Theegala":"Sahith Theegara","Rasmus Neergaard-Petersen":"Rasmus Neergaard-Pedersen",
"Haotong Li":"Haotong Lin","Andrew Putnam":"Andrew Putman","Taylor Pendrith":"Taylor Pendreth","Alex Fitzpatrick":"Alex Fitzpatrice",
"Max McGreevy":"Max McGreavy","J.T. Poston":"J.T. Postin","John Parry":"John Perry","Austin Smotherman":"Austin Smithers",
"Christiaan Bezuidenhout":"Christiaan Bezuidenhof","Richard Hoey":"Richard Hoye","Lucas Herbert":"Lucas Hebert","Daniel Hillier":"Daniel Hillyer",
"Ricky Castillo":"Ricky Castilla","Stephan Jaeger":"Stephan Jaeggi","Garrick Higgo":"Garrick Higson","Tony Finau":"Tony Finao",
"Neal Shipley":"Neal Shipman","John VanDerLaan":"John VanDerLinde","Lanto Griffin":"Lanto Griffith","Tom Hoge":"Tom Hogue",
"Taylor Moore":"Taylor Moores","Hank Lebioda":"Hank Lebeda","Brice Garnett":"Brice Garnier","David Lipsky":"David Lipscomb",
"Chris Kirk":"Chris Kirke","Lucas Glover":"Lucas Glovers","Denny McCarthy":"Denny McCartney","Shaun Norris":"Shaun Norrie",
"Elvis Smylie":"Elvis Smiley","Erik van Rooyen":"Erik van Rooijen","Thorbjorn Olesen":"Thorbjorn Olsen","Adrian Meronk":"Adrian Meronski",
"Victor Perez":"Victor Perrez","Romain Langasque":"Romain Langlasque","Antoine Rozner":"Antoine Rozier","Matthieu Pavon":"Matthieu Pavot",
"Max Homa":"Max Homer","Adrien Saddier":"Adrien Saddler","Marcus Armitage":"Marcus Armstrong","Daniel Brown":"Daniel Browne",
"Dan Bradbury":"Dan Bradbourne","Callum Tarren":"Callum Tarrant","David Skinns":"David Skinner","Ben Kohles":"Ben Kohler",
"Chad Ramey":"Chad Ramsey","Chan Kim":"Chan Kang","Vince Whaley":"Vince Whalen","Kevin Roy":"Kevin Royce",
"Patrick Fishburn":"Patrick Fishbourne","Jimmy Stanger":"Jimmy Stanger-Jones","Chandler Phillips":"Chandler Philips","Hayden Springer":"Hayden Springfield",
"Chandler Blanchet":"Chandler Blanchard","Gordon Sargent":"Gordon Sergeant","Peter Malnati":"Peter Malnatti","Will Gordon":"Will Gordo",
"Sam Ryder":"Sam Rider","Luke Clanton":"Luke Clayton","Davis Riley":"Davis Reilly","Joe Highsmith":"Joe Highsmythe",
"Justin Lower":"Justin Lowery","Taylor Montgomery":"Taylor Montgomerie","Danny Walker":"Danny Walkden","Patton Kizzire":"Patton Kizer",
"Nick Dunlap":"Nick Dunlop","Kensei Hirata":"Kensei Hirota","Carson Young":"Carson Youngs","Kevin Streelman":"Kevin Steelman",
"Brandt Snedeker":"Brandt Sneddon","Webb Simpson":"Webb Simmons","Zach Johnson":"Zach Johnston","Stewart Cink":"Stewart Fink",
"Ryan Moore":"Ryan Moores","Chez Reavie":"Chez Reavey","Brian Stuard":"Brian Stuart","Joel Dahmen":"Joel Dahman",
"Beau Hossler":"Beau Hosler","Mark Hubbard":"Mark Hubbert","Jhonattan Vegas":"Jhonattan Vargas","Jeffrey Kang":"Jeffrey Kwang",
"Greyson Sigg":"Greyson Siggs","Luke List":"Luke Liszt","Doug Ghim":"Doug Ghimm","Dylan Wu":"Dylan Woo",
"Adam Schenk":"Adam Schenck","Henrik Norlander":"Henrik Norland","Jesper Svensson":"Jesper Sveningsson","Vincent Norrman":"Vincent Norman",
"Tim Widing":"Tim Wideling","Adam Svensson":"Adam Svenson","Adam Hadwin":"Adam Hadwen","Rafael Campos":"Rafael Campo",
"Brian Campbell":"Brian Cambell","Marcelo Rozo":"Marcelo Rojo","Ben Silverman":"Ben Silverstein","Roger Sloan":"Roger Sloane",
"Christo Lamprecht":"Christo Lambrecht","Camilo Villegas":"Camilo Villega","Sebastian Munoz":"Sebastian Munez","Mito Pereira":"Mito Pereyra",
"Cristobal Del Solar":"Cristobal Del Sol","Alejandro Tosti":"Alejandro Tosto","Fabian Gomez":"Fabian Gomes","MJ Daffue":"MJ Daffy",
"Thriston Lawrence":"Thriston Laurence","Dean Burmester":"Dean Burmeister","Dylan Frittelli":"Dylan Fritelli","Zander Lombard":"Zander Lombardi",
"Ockie Strydom":"Ockie Strydon","Kazuki Higa":"Kazuki Higo","Ryo Ishikawa":"Ryo Ishida","Takumi Kanaya":"Takumi Kanaga",
"Keita Nakajima":"Keita Nakamura","Rikuya Hoshino":"Rikuya Hoshida","Yuta Sugiura":"Yuta Sugimura","S.H. Kim":"S.H. Kang",
"K.H. Lee":"K.H. Leigh","Bio Kim":"Bio Kang","Wenyi Ding":"Wenyi Deng","Carl Yuan":"Carl Yuen","Marty Dou":"Marty Dao",
"Gaganjeet Bhullar":"Gaganjeet Bhalla","Shubhankar Sharma":"Shubhankar Sharman","Anirban Lahiri":"Anirban Lahari","Yannik Paul":"Yannik Pauls",
"Marcel Siem":"Marcel Siemens","Maximilian Kieffer":"Maximilian Kiefer","Guido Migliozzi":"Guido Miglioretti","Francesco Molinari":"Francesco Molinaro",
"Edoardo Molinari":"Edoardo Molinaro","Renato Paratore":"Renato Paratori","Matteo Manassero":"Matteo Manassera","Pablo Larrazabal":"Pablo Larrazaga",
"Jorge Campillo":"Jorge Campilla","Nacho Elvira":"Nacho Elvero","Angel Hidalgo":"Angel Hidalga","Eugenio Chacarra":"Eugenio Chacarro",
"Alejandro Del Rey":"Alejandro Del Real","Connor Syme":"Connor Symes","Ewen Ferguson":"Ewen Fergusson","Calum Hill":"Calum Hills",
"Grant Forrest":"Grant Forrester","Richie Ramsay":"Richie Ramsey","David Law":"David Lawe","Padraig Harrington":"Padraig Harringford",
"Seamus Power":"Seamus Powers","Tom McKibbin":"Tom McKibben","Niklas Norgaard":"Niklas Norgard",
}
LEGENDS = {
"Tiger Woods":"Tyger Woodes","Jack Nicklaus":"Jack Nicklin","Ben Hogan":"Ben Hogarth","Sam Snead":"Sam Sneed","Arnold Palmer":"Arnold Palmar",
"Gary Player":"Gary Playter","Tom Watson":"Tom Watsham","Seve Ballesteros":"Seve Ballestero","Nick Faldo":"Nick Faldon","Greg Norman":"Greg Normand",
"Phil Mickelson":"Phil Mickleson","Lee Trevino":"Lee Trevini","Byron Nelson":"Byron Nelsen","Gene Sarazen":"Gene Sarazin","Walter Hagen":"Walter Hagan",
"Bobby Jones":"Bobby Joynes","Vijay Singh":"Vijay Singha","Ernie Els":"Ernie Elsen","Nick Price":"Nick Pryce","Raymond Floyd":"Raymond Floyde",
"Johnny Miller":"Johnny Millar","Payne Stewart":"Payne Steward","Curtis Strange":"Curtis Strand","Billy Casper":"Billy Caspar",
"Cary Middlecoff":"Cary Middlecott","Lloyd Mangrum":"Lloyd Mangram","Horton Smith":"Horton Smyth","Harry Cooper":"Harry Couper",
"Jimmy Demaret":"Jimmy Demarest","Leo Diegel":"Leo Diegal","Gene Littler":"Gene Littleton","Paul Runyan":"Paul Runyon","Henry Picard":"Henry Pickard",
"Tommy Armour":"Tommy Armor","Macdonald Smith":"Macdonald Smyth","Harry Vardon":"Harry Vardan","Peter Thomson":"Peter Thompsen","James Braid":"James Brayd",
}
EVENTS = {
"Sony Open":"Waialae Open","The American Express":"The Desert Classic","Farmers Insurance Open":"Torrey Pines Open","WM Phoenix Open":"The Desert Stadium Open",
"AT&T Pebble Beach Pro-Am":"Pebble Coast Pro-Am","The Genesis Invitational":"The Riviera Invitational","Cognizant Classic":"The Palm Beach Classic",
"Arnold Palmer Invitational":"The Bay Hill Invitational","The Players Championship":"The Pros' Championship","Valspar Championship":"The Copperhead Championship",
"Houston Open":"Houston Open","Valero Texas Open":"The Texas Open","The Masters":"The Magnolia Masters","RBC Heritage":"The Harbour Heritage",
"Zurich Classic (Pairs)":"New Orleans Classic (Pairs)","Miami Championship":"Miami Championship","Truist Championship":"The Charlotte Championship",
"PGA Championship":"SPA Championship","CJ Cup Byron Nelson":"The Dallas Classic","Charles Schwab Challenge":"The Colonial Challenge",
"The Memorial":"The Memorial","RBC Canadian Open":"The Canadian Open","U.S. Open":"The National Open","Travelers Championship":"The Connecticut Championship",
"John Deere Classic":"The Quad Cities Classic","Genesis Scottish Open":"The Scottish Open","The Open Championship":"The Links Championship",
"3M Open":"The Twin Cities Open","Wyndham Championship":"The Greensboro Championship","FedEx St. Jude Championship":"The Memphis Championship",
"BMW Championship":"The St. Louis Championship","Tour Championship":"Tour Championship",
"Puntacana Championship":"The Caribbean Championship","Myrtle Beach Classic":"Myrtle Beach Classic","Barracuda Championship":"The Tahoe Championship",
"ISCO Championship":"The Kentucky Championship","Barbasol Championship":"The Bluegrass Championship",
}
TERMS = {  # brand words used across the game's text
"Ryder Cup":"Transatlantic Cup","Presidents Cup":"Continents Cup","FedEx Cup":"Tour Cup","FedEx":"Tour Cup","PGA Tour":"SPA Tour",
"World Cup of Golf":"World Cup of Golf","OWGR":"World Ranking",
}
COURSES = {
"Augusta National":"Magnolia National","TPC Sawgrass (Stadium)":"Ponte Vedra (Stadium)","PGA National (Champion)":"Palm Beach National (Champion)",
"PGA West (Stadium)":"La Quinta West (Stadium)","Trump National Doral (Blue Monster)":"Doral (Blue Monster)",
}
for _t in ['Craig Ranch', 'Deere Run', 'Harding Park', 'Louisiana', 'River Highlands', 'San Antonio', 'Scottsdale', 'Southwind', 'Toronto', 'Twin Cities']:
    COURSES['TPC ' + _t] = _t + ' Stadium Club'
COURSES['TPC Sawgrass'] = 'Ponte Vedra'
